# Generated by Django 4.1.3 on 2022-11-15 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='available_for_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='location',
            field=models.CharField(default='Egypt', max_length=150),
        ),
        migrations.AddField(
            model_name='coach',
            name='price_per_30_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='price_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coach',
            name='speciality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
