# Generated by Django 4.1.3 on 2022-12-15 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coach_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 15, 16, 45, 16, 501836, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
