# Generated by Django 4.1.3 on 2022-11-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_coach_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='role',
        ),
    ]
