# Generated by Django 4.1.3 on 2022-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_client_city_remove_client_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
