# Generated by Django 4.1.3 on 2022-11-15 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_client_role_remove_coach_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
