# Generated by Django 4.1.3 on 2022-12-31 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='not-provided', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='not-provided', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='joined_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 15, 5, 25, 491192)),
        ),
    ]
