# Generated by Django 4.1.3 on 2022-12-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
