# Generated by Django 4.1.3 on 2022-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/client/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/coach/%Y/%m/%d'),
        ),
    ]
