# Generated by Django 4.1.3 on 2022-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
