# Generated by Django 4.1.3 on 2022-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_session_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='session',
            name='group_session',
            field=models.BooleanField(default=False),
        ),
    ]
