# Generated by Django 4.1.3 on 2023-01-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_client_photo_alter_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
