# Generated by Django 4.1.3 on 2023-01-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_coach_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='certificate/coach')),
            ],
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='brief',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='coach',
            name='certificates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.certificate'),
        ),
    ]
