# Generated by Django 4.1.3 on 2022-11-25 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_client_user_alter_coach_user_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='working_hours_end',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='coach',
            name='working_hours_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
