# Generated by Django 4.1.3 on 2023-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_certificate_rename_brief_coach_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='not-provided', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='not-provided', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/client/%Y/%m/%d'),
        ),
    ]
