# Generated by Django 4.1.3 on 2022-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_coach_working_hours_end_coach_working_hours_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='home.session'),
        ),
    ]
