# Generated by Django 4.1.3 on 2023-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_client_city_remove_client_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/client/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(upload_to='photo/coach/%Y/%m/%d'),
        ),
    ]
