# Generated by Django 4.1.3 on 2022-11-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
