# Generated by Django 4.1.3 on 2023-01-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_photo_client_photo_alter_coach_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='speciality',
            new_name='category',
        ),
    ]
