# Generated by Django 4.1.3 on 2023-01-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_speciality_coach_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='category',
        ),
        migrations.AlterField(
            model_name='coach',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
