# Generated by Django 4.1.3 on 2022-11-26 12:43

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_order_items_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_address', models.CharField(max_length=150)),
                ('chipment_phone', models.CharField(max_length=150)),
                ('card_number', creditcards.models.CardNumberField(max_length=25)),
                ('expiry_date', creditcards.models.CardExpiryField()),
                ('security_code', creditcards.models.SecurityCodeField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
