# Generated by Django 4.1.3 on 2023-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_session_category_alter_coach_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='certificates',
        ),
        migrations.AddField(
            model_name='coach',
            name='certificates',
            field=models.ManyToManyField(to='home.certificate'),
        ),
    ]
