# Generated by Django 4.1.3 on 2022-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_payment_session_url_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
