# Generated by Django 4.1.3 on 2023-01-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_coach_certificates_coach_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coach'),
        ),
    ]
