# Generated by Django 4.1.3 on 2023-01-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_coach_certificates_certificate_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='certificates', to='home.coach'),
        ),
    ]
