# Generated by Django 4.1.3 on 2022-11-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderdetails_order_delete_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
